### ISSUE TITLE
Great scripts!

### ISSUE THREAD

**Issue by michaeldbeard** [DarklightGames/io_scene_ase#1]
Seemed to work very well.  The error message stating "No UV"  did not give me a hint as to where to go in Blender to add one.  The message about adding a "Mesh" did not give me any hints either, but then "The mesh needs at least one material was even less helpful when I do not know Blender.

I guess I was hoping for an Import, then an Export, with no intervening steps.  Too much to hope for, apparently.  I guess I will have to learn Blender more to be able to use it effectively for my student's benefits.

**Comment by davidoskky** [comment]
Dear Michael, I started using this script just a few days ago, so I am not the most expert on the matter.
Both problems you are getting are due to the missing information of how to place textures on your model.
The video linked in the readme of the script explains how to avoid having such problem. I suggest you watch that video as it goes into detail.
You just have to make sure you created a material and an UV map for every object in your model, you don't necessarily need to use textures but you need to create at least one placeholder material.
