### ISSUE TITLE
Meshes with high polygon counts export incorrectly

### ISSUE THREAD

**Issue by Lasercar** [DarklightGames/io_scene_ase#4]
~~Same problem as the psk/psa exporter addon, exports above a set limit of verts and triangles get artifacts and lose parts of the mesh.~~

Edit: I got confused with both this new project and the older one (Yet I somehow still made the issue here?). Anyway, the issue title still applies, but rather than stopping at a set limit (like the old version), it messes up the triangles after a certain point:
![Capture](https://user-images.githubusercontent.com/64717068/196038340-0c84c64c-4416-4bc8-bdc1-21b5746b95fe.PNG)
I'm updating this model import to replace the auto smoothing and giving it's original smoothing/sharp edges, so you might not be able to replicate this on your end with the model from the addon.

**Comment by cmbasnett** [comment]
@Lasercar could you post the blend file that you used to produce the bug?

**Comment by Lasercar** [comment]
@cmbasnett Sure. Unreal will take its sweet time to import it though, the exported file is 23MB. 
[HPScorpion.zip](https://github.com/DarklightGames/io_scene_ase/files/9885987/HPScorpion.zip)

**Comment by cmbasnett** [comment]
It appears that there are hard limits on the amount of elements (i.e., vertices, triangles etc.) allowed in an ASE export when importing into Unreal. This is not *technically* a bug with the exporter, since the ASE file format doesn't specify any of these limitations, and the bug is a result of a deficiency in the Unreal engine where it doesn't enforce its own limitations.

If I can be given a list of the actual element limitations for the format in Unreal, I can code in a warning that the mesh will not import correctly into Unreal engine.

**Comment by cmbasnett** [comment]
Going to close this since this is not actually an issue with the exporter, but of handling within the engine importer.
